version: '2.4'

networks:
  network:
    driver: bridge

x-common-variables: &common-variables
  MONGO_CONNECTION: mongodb://testing:E6aQHs56&u@mongo:27017/tinder

services:
  mongo:
    image: bitnami/mongodb
    ports:
      - 27017:27017
    restart: always
    networks:
      - network
    environment:
      MONGODB_DATABASE: tinder
      MONGODB_USERNAME: testing
      MONGODB_PASSWORD: E6aQHs56&u
      MONGODB_ROOT_USER: tinder
      MONGODB_ROOT_PASSWORD: Bq8FD74#%9
    logging:
      driver: none
    
  # tinder-api:
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile
  #   ports:
  #     - 80:3000
  #   networks:
  #     - network
  #   environment: 
  #     <<: *common-variables
  #   command: 
  #     - node
  #     - "dist/src/server.js"
  